version: '3'
services:
  apache-php:
    build:
      context: ./docker/apachephp
    image: devbox
    container_name: apachephp
    ports:
      - "9999:80"
    volumes:
      - "./:/var/www/"
    networks:
      - back-network
networks:
  back-network:
    driver: bridge
volumes:
  cinema:

